#! /usr/bin/env python

def build(bld):
	bld.new_task_gen(
		features = 'cxx cprogram',
		source = 'yc20.cc',
		target = 'yc20',
		includes = "../",
		uselib_local = "libttsoot jackgtkmm",
		uselib = "GTKMM-2.4 JACK" )

	bld.new_task_gen(
		features = 'cxx cprogram',
		source = 'funny_delay.cc',
		target = 'funny_delay',
		includes = "../",
		uselib_local = "libttsoot jackgtkmm",
		uselib = "GTKMM-2.4 JACK" )

	bld.new_task_gen(
		features = 'cxx cprogram',
		source = 'simple_synth.cc',
		target = 'simple_synth',
		includes = "../",
		uselib_local = "libttsoot jackgtkmm",
		uselib = "GTKMM-2.4 JACK" )

	bld.new_task_gen(
		features = 'cxx cshlib',
		source = 'lv2delay.cc',
		target = 'lv2delay',
		includes = "../",
		uselib_local = "libttsoot",
		uselib = "" )
