#! /usr/bin/env python

def build(bld):
	bld.new_task_gen(
		features = 'cxx cprogram',
		source = 'yc20.cc',
		target = 'yc20',
		includes = "../",
		uselib_local = "libttsoot jackgtkmm",
		uselib = "GTKMM-2.4 JACK" )

