#! /usr/bin/env python

def configure(conf):
    conf.check_cfg( package="gtkmm-2.4", args="--cflags --libs" )
    conf.check_cfg( package="jack", args="--cflags --libs" )

def build(bld):
	bld.new_task_gen(
		features = 'cxx cstaticlib',
		source = 'gui.cc gui_adjustment.cc main.cc',
		target = 'jackgtkmm',
		includes = "../",
		uselib = "GTKMM-2.4 JACK")

