#! /usr/bin/env python

def configure(conf):
    conf.check_cfg( package="gtkmm-2.4", args="--cflags --libs" )
    conf.check_cfg( package="jack", args="--cflags --libs" )

def build(bld):
	bld.new_task_gen(
		features = 'cxx cstaticlib',
		source = 'gui.cc gui_adjustment.cc gui_knob.cc gui_slider.cc gui_meter.cc main.cc',
		target = 'jackgtkmm',
		includes = "../",
		uselib = "GTKMM-2.4 JACK")

	bld.new_task_gen(
		features = 'cxx cstaticlib',
		source = 'gui_adjustment.cc gui_knob.cc gui_slider.cc gui_meter.cc',
		target = 'ttgui',
		includes = "../",
		uselib = "GTKMM-2.4 JACK")

	bld.new_task_gen(
		features = 'cxx cprogram',
		source = 'ttm.cc ttm_engine.cc ttm_gui.cc',
		target = 'ttm',
		includes = "../",
		uselib_local = "ttgui",
		uselib = "GTKMM-2.4 JACK" )

